
const kids = {
    id: 'kids',
    products: [
        {
            id: 'kids1',
            title: 'Coated glitter chuck taylor all star',
            price: 261,
            img: '/img/Coated glitter chuck taylor all star.png',
            brand: 'Converse',
            sku: '1234567890',
            color: ['Purple', 'Pink'],
            size: ['M', 'L'],
            category: 'kids',
        },
        {
            id: 'kids2',
            title: 'Chuck taylor all star',
            price: 504,
            img: '../../img/Chuck taylor all star.png',
            brand: 'Nike',
            sku: '1234567891',
            color: ['Purple', 'Pink'],
            size: ['XS', 'S'],
            category: 'kids',
        },
        {
            id: 'kids3',
            title: 'Continental 80 shoes',
            price: 126,
            img: '../../img/Continental 80 shoes.png',
            brand: 'Adidas',
            sku: '1234567892',
            color: ['Purple', 'Pink'],
            size: ['S', 'M'],
            category: 'kids',
        },
        {
            id: 'kids4',
            title: 'Swift run x shoes',
            price: 337,
            img: '../../img/Swift run x shoes.png',
            brand: 'Adidas',
            sku: '1234567893',
            color: ['Purple', 'Pink'],
            size: ['X', 'L'],
            category: 'kids',
        },
        {
            id: 'kids5',
            title: 'Nmd r1 shoes',
            price: 537,
            img: '../../img/Nmd r1 shoes.png',
            brand: 'Adidas',
            sku: '1234567894',
            color: ['Purple', 'Pink'],
            size: ['X', 'XL'],
            category: 'kids',
        }
    ]
}

const women = {
    id: 'women',
    products: [
        {
            id: 'women1',
            title: 'Nike revolution 5',
            price: 255,
            img: '/img/Nike revolution 5.png',
            brand: 'Nike',
            sku: '1234567890',
            color: ['Brown'],
            size: ['S', 'M', 'L'],
            category: 'women',
        },
        {
            id: 'women2',
            title: 'Nike court vision low',
            price: 904,
            img: '../../img/Nike court vision low.png',
            brand: 'Nike',
            sku: '1234567891',
            color: ['White'],
            size: ['XS', 'S'],
            category: 'women',
        },
        {
            id: 'women3',
            title: 'Nike odyssey react flyknit 2',
            price: 875,
            img: '../../img/Nike odyssey react flyknit 2.png',
            brand: 'Nike',
            sku: '1234567892',
            color: ['Pink'],
            size: ['S', 'XL'],
            category: 'women',
        },
        {
            id: 'women4',
            title: 'Nike drop-type premium',
            price: 257,
            img: '../../img/Nike drop-type premium.png',
            brand: 'Nike',
            sku: '1234567893',
            color: ['White'],
            size: ['M', 'L', 'XL'],
            category: 'women',
        },
        {
            id: 'women5',
            title: 'Nike air presto by you',
            price: 327,
            img: '../../img/Nike air presto by you.png',
            brand: 'Adidas',
            sku: '1234567894',
            color: ['Green'],
            size: ['XS', 'S','XL'],
            category: 'women',
        },
        {
            id: 'women6',
            title: 'Seasonal color chuck 70',
            price: 124,
            img: '../../img/Seasonal color chuck 70.png',
            brand: 'Converse',
            sku: '1234567894',
            color: ['Purple'],
            size: ['XS', 'S', 'M'],
            category: 'women',
        },
        {
            id: 'women7',
            title: 'Chuck taylor all star move',
            price: 432,
            img: '../../img/Chuck taylor all star move.png',
            brand: 'Converse',
            sku: '1234567894',
            color: ['Pink'],
            size: [ 'S', 'M'],
            category: 'women',
        },
        {
            id: 'women8',
            title: 'Jack purcell leather',
            price: 264,
            img: '../../img/Jack purcell leather.png',
            brand: 'Converse',
            sku: '1234567894',
            color: ['White'],
            size: ['XS', 'S', 'M'],
            category: 'women',
        },
        {
            id: 'women9',
            title: 'Custom chuck taylor all star by you',
            price: 426,
            img: '../../img/Custom chuck taylor all star by you.png',
            brand: 'Converse',
            sku: '1234567894',
            color: ['Purple'],
            size: [ 'S', 'L'],
            category: 'women',
        },
        {
            id: 'women10',
            title: 'Senseboost go shoes',
            price: 231,
            img: '../../img/Senseboost go shoes.png',
            brand: 'Adidas',
            sku: '1234567894',
            color: ['Black'],
            size: [ 'S', 'M', 'XL'],
            category: 'women',
        },
        {
            id: 'women11',
            title: 'Lite racer adapt 3.0 shoes',
            price: 948,
            img: '../../img/Lite racer adapt 3.0 shoes.png',
            brand: 'Adidas',
            sku: '1234567894',
            color: ['White'],
            size: [ 'S', 'L'],
            category: 'women',
        }

    ]
}
const men = {
    id: 'men',
    products: [
        {
            id: 'men1',
            title: 'Nike air zoom pegasus 35',
            price: 642,
            img: '/img/Nike air zoom pegasus 35.png',
            brand: 'Nike',
            sku: '1234567890',
            color: ['Blue'],
            size: ['S', 'L'],
            category: 'men',
        },
        {
            id: 'men2',
            title: 'Seasonal color chuck 70',
            price: 126,
            img: '../../img/Seasonal color chuck 70.png',
            brand: 'Converse',
            sku: '1234567892',
            color: ['Blue'],
            size: ['S', 'M'],
            category: 'men',
        },
        {
            id: 'men3',
            title: 'Hacked fashion chuck taylor all star',
            price: 141,
            img: '../../img/Hacked fashion chuck taylor all star.png',
            brand: 'Converse',
            sku: '1234567893',
            color: ['Blue'],
            size: ['M', 'L'],
            category: 'men',
        },
        {
            id: 'men4',
            title: 'Nizza trefoil shoes',
            price: 137,
            img: '../../img/Nizza trefoil shoes.png',
            brand: 'Adidas',
            sku: '1234567894',
            color: ['White'],
            size: ['XS','M', 'XL'],
            category: 'men',
        },
        {
            id: 'men5',
            title: 'Strutter shoes',
            price: 375,
            img: '../../img/Strutter shoes.png',
            brand: 'Adidas',
            sku: '1234567894',
            color: ['White'],
            size: ['XS', 'XL'],
            category: 'men',
        }
    ]
}

export { kids , women, men }